### ISSUE TITLE
Typo in English language string

### ISSUE THREAD

**Issue by germanvaleroelizondo** [rezaies/moodle-profilefield_associated#1]
Hi,
I was translating the https://moodle.org/plugins/view/profilefield_associated plugin and I noticed a small typo:

 dupplicateassociated | profilefield_associated

Another custom profile field is already associated with the selected ptofile field.

'ptofile' should be 'profile' (I think).

Thanks in advance for your help.

**Comment by rezaies** [comment]
Thank.

Fixed: https://github.com/rezaies/moodle-profilefield_associated/commit/6b6b0a902879647dd761d8dfb32a84a2b8c73d93
